- name: "Router configuration"
  hosts: localhost
  become: yes
  tasks:
  - name: Route all traffic to public
    ansible.builtin.iptables:
      state: "present"
      table: "nat"
      chain: "POSTROUTING"
      jump: "MASQUERADE"
      out_interface: "enp0s9"
  - name: Route traffic from outside to inside
    ansible.builtin.iptables:
      state: "present"
      chain: "FORWARD"
      jump: "ACCEPT"
      in_interface: "enp0s9"
      out_interface: "enp0s8"
      match: state
      ctstate:
        - RELATED
        - ESTABLISHED
  - name: Route traffic from outside to inside
    ansible.builtin.iptables:
      state: "present"
      chain: "FORWARD"
      jump: "ACCEPT"
      in_interface: "enp0s8"
      out_interface: "enp0s9"

